### ISSUE TITLE
Need some direction

### ISSUE THREAD

**Issue by unional** [typed-typings/env-atom#1]
@blakeembrey , I try to work on this but need some guidance.
1. I'm getting error on `atom.d.ts`: "Invalid module name in augmentation, module 'atom' cannot be found"
2. Am I doing the right thing inside `declare module 'atom' { ...}`? I don't think I'm doing it right.

The use case should be (:

``` ts
import atom = require('atom');

atom.commands  // AtomEnvironment
atom.Disposable
```

Here is their API doc:
https://atom.io/docs/api/v1.5.3/AtomEnvironment

**Comment by blakeembrey** [comment]
Atom is an environment, not an NPM module. I think Atom should be typed as an ambient module instead. Does that make sense? Otherwise things are being wrapped up, which is what's happening with you now.

**Comment by unional** [comment]
`atom` exposes a global `atom`, and also through require:
https://atom.io/docs/api/v1.5.3/CompositeDisposable

``` coffee
{CompositeDisposable} = require 'atom'

class Something
  constructor: ->
    @disposables = new CompositeDisposable
    editor = atom.workspace.getActiveTextEditor()
    @disposables.add editor.onDidChange ->
    @disposables.add editor.onDidChangePath ->

  destroy: ->
    @disposables.dispose()
```

**Comment by unional** [comment]
The global `atom` is an instance of `AtomEnvironment`. It does not has a reference to `CompositeDisposable` (for example).  i.e., `atom.CompositeDisposable === undefined`

**Comment by unional** [comment]
> I think Atom should be typed as an ambient module instead.

I do set `ambient: true` in the `typings.json`.  Do you mean the repo should be named as `ambient-atom`?

**Comment by blakeembrey** [comment]
What about `env-atom` as the repo name? You also need to install it with ambient, so `typings install ... --ambient` to make sure no wrapping occurs (got to error in 0.7 when `ambient: true` is enabled).

**Comment by unional** [comment]
Yes Sir! I'm all for `env-atom` :+1:
