### ISSUE TITLE
Simplify AtomEnviornment

### ISSUE THREAD

**Issue by unional** [typed-typings/env-atom#2]
@blakeembrey 

Currently I have to duplicate things in both `AtomEnviornment` and `declare namespace atom`. They are actually the same.

Any way to simplify this?

**Comment by blakeembrey** [comment]
Off-topic, but I didn't see this: https://github.com/typed-typings/env-atom/blob/master/index.d.ts#L2. Isn't this incorrect for everything inside now? You've broken all interface and class access on the atom namespace? Instead of `atom.Clipboard` it's now `atom.Typings.Clipboard` which doesn't map to anything at runtime.

Could you share the duplicated parts?

**Comment by unional** [comment]
The duplicated part is:

``` ts
declare namespace atom {
  namespace Typings {
    export interface AtomEnvironment {
      commands: CommandRegistry;  // <-- here
      ...
    }
   export var commands: Typings.CommandRegistry; // <-- here
   ....
}
```

The global `atom` is an instance of AtomEnvironment. I could have:

``` ts
interface AtomEnviornment { ... }
declare var atom: AtomEnvironment;
```

But then I can't expose the types (CommandRegistry, etc) under the "`atom` global namespace".

> Isn't this incorrect for everything inside now?

Those are types, not used directly. `atom.clipboard` is an instance of `atom.Typings.Clipboard`. 
They do not expose the class directly (as `atom` is an instance of `AtomEnviornment`).

**Comment by blakeembrey** [comment]
I guess that global `atom` has been wiped out now? Was just trying to review it, but I don't think there's a better way than what you've already got.

**Comment by unional** [comment]
> I guess that global atom has been wiped out now

It is still there, in `lib/atom-namespace.d.ts`. The whole things is in there.

**Comment by blakeembrey** [comment]
Right, I couldn't find `declare var atom: AtomEnvironment;` anymore though. It looks like you fixed it by using the `namespace atom`?

**Comment by unional** [comment]
Yes. The `declare var atom:...` just wouldn't work. That's why i currently do `declare namespace atom {...}` (with the duplication).

So there is no way to make `declare var atom: AtomEnvironment` work? I hate duplicate stuff. :stuck_out_tongue:

**Comment by unional** [comment]
Close this issue until someone complains. :smirk:
