### ISSUE TITLE
Better way to re-export in named export?

### ISSUE THREAD

**Issue by unional** [typed-typings/env-atom#3]
Since script/global cannot have `import`, I have to put all typings into `atom.Typings.*`. 
In the `atom` and `event-kit` module, currently I have to do a dummy extend to re-export the classes.

Is there a better way?

https://github.com/typed-typings/env-atom/blob/master/lib/atom.d.ts

``` ts
/// <reference path="atom-namespace.d.ts" />

declare module 'atom' {
  export class BufferedNodeProcess extends atom.Typings.BufferedNodeProcess {}
  export class BufferedProcess extends atom.Typings.BufferedProcess {}
  export class CompositeDisposable extends atom.Typings.CompositeDisposable {}
  export class Task extends atom.Typings.Task {}
}
```

**Comment by unional** [comment]
@blakeembrey any idea?

**Comment by blakeembrey** [comment]
Seems reasonable. That's the only way when working with globals. I think you can also do:

``` ts
export var BufferedNodeProcess: typeof atom.Typings.BufferedNodeProcess
```

**Comment by unional** [comment]
> export var BufferedNodeProcess: typeof atom.Typings.BufferedNodeProcess

That would be much more preferable. :+1:

**Comment by unional** [comment]
Done

**Comment by unional** [comment]
Actually a drawback.

``` ts
export var BufferedNodeProcess: typeof atom.Typings.BufferedNodeProcess
```

declares it as variable, so the icon on vscode completion is incorrect.
