### ISSUE TITLE
Class constructors undefined

### ISSUE THREAD

**Issue by banacorn** [typed-typings/env-atom#6]
I can reference some types such as `Point` like this:

``` js
let p: atom.Typings.Point;
```

But not it's constructor:

``` js
let p = new atom.Typings.Point(1, 2);
```

The line above can be type checked, but will crash on runtime, because `atom.Typings` is `undefined`, am I using it the wrong way?

**Comment by unional** [comment]
Very valid point. When I created the typings I was expecting everything under `atom.Typings` to contain interface only, not class. It does not work with class.

I painstakingly went through the whole document to add all typings in. But for those classes I didn't know how to access them (it was not described in the doc).

As now I look into it, it is from here: https://github.com/atom/text-buffer/blob/master/src/point.coffee

Do you know how to access it in js? We can then refactor it to put it in the right place.

**Comment by unional** [comment]
Ok. I found it. It can be accessed under:

``` ts
import a = require('atom');
a.Point;
a.TextBuffer.Point;
```

Will see if I can pull the relevant types into the module (instead of the global `atom`)

**Comment by banacorn** [comment]
Yes, it can be accessed like that, but the typechecker would complain.

While these classes seem perfectly fine to be accessed.

``` ts
/// <reference path="./atom-namespace.d.ts" />

declare module 'atom' {
  export var BufferedNodeProcess: atom.Typings.BufferedNodeProcess;
  export var BufferedProcess: atom.Typings.BufferedProcess;
  export var CompositeDisposable: atom.Typings.CompositeDisposable;
  export var Task: atom.Typings.Task;
}
```

**Comment by banacorn** [comment]
I think we should move everything to the module while leaving only the properties of [AtomEnvironment](https://atom.io/docs/api/v1.7.4/AtomEnvironment) in the global `atom`.

**Comment by unional** [comment]
Yes. That what I mean by "pull the relevant types into the module"

**Comment by unional** [comment]
Actually there are many things on the `AtomEnvironment`:

``` ts
      "blobStore",
      "applicationDelegate",
      "window",
      "document",
      "configDirPath",
      "enablePersistence",
      "unloaded",
      "loadTime",
      "emitter",
      "disposables",
      "stateStore",
      "deserializers",
      "deserializeTimings",
      "views",
      "notifications",
      "config",
      "keymaps",
      "tooltips",
      "commands",
      "grammars",
      "styles",
      "packages",
      "themes",
      "menu",
      "contextMenu",
      "clipboard",
      "project",
      "appVersion",
      "commandInstaller",
      "workspace",
      "textEditors",
      "autoUpdater",
      "initialStyleElements",
      "stylesElement",
      "previousWindowErrorHandler",
      "windowEventHandler",
      "constructor",
      "lastUncaughtError",
      "saveStateDebounceInterval",
      "attachSaveStateListeners",
      "setConfigSchema",
      "registerDefaultDeserializers",
      "registerDefaultCommands",
      "registerDefaultViewProviders",
      "registerDefaultOpeners",
      "registerDefaultTargetForKeymaps",
      "observeAutoHideMenuBar",
      "reset",
      "destroy",
      "onDidBeep",
      "onWillThrowError",
      "onDidThrowError",
      "onDidFailAssertion",
      "inDevMode",
      "inSafeMode",
      "inSpecMode",
      "isFirstLoad",
      "getVersion",
      "getReleaseChannel",
      "isReleasedVersion",
      "getWindowLoadTime",
      "getLoadSettings",
      "open",
      "pickFolder",
      "close",
      "getSize",
      "setSize",
      "getPosition",
      "setPosition",
      "getCurrentWindow",
      "center",
      "focus",
      "show",
      "hide",
      "reload",
      "isMaximized",
      "maximize",
      "isFullScreen",
      "setFullScreen",
      "toggleFullScreen",
      "displayWindow",
      "getWindowDimensions",
      "setWindowDimensions",
      "isValidDimensions",
      "storeWindowDimensions",
      "getDefaultWindowDimensions",
      "restoreWindowDimensions",
      "restoreWindowBackground",
      "storeWindowBackground",
      "startEditorWindow",
      "serialize",
      "unloadEditorWindow",
      "openInitialEmptyEditorIfNecessary",
      "installUncaughtErrorHandler",
      "uninstallUncaughtErrorHandler",
      "installWindowEventHandler",
      "uninstallWindowEventHandler",
      "beep",
      "confirm",
      "openDevTools",
      "toggleDevTools",
      "executeJavaScriptInDevTools",
      "assert",
      "loadThemes",
      "watchProjectPaths",
      "setDocumentEdited",
      "setRepresentedFilename",
      "addProjectFolder",
      "showSaveDialog",
      "showSaveDialogSync",
      "saveBlobStoreSync",
      "saveState",
      "loadState",
      "deserialize",
      "getStateKey",
      "getStorageFolder",
      "getConfigDirPath",
      "getUserInitScriptPath",
      "requireUserInitScript",
      "onUpdateAvailable",
      "updateAvailable",
      "listenForUpdates",
      "setBodyPlatformClass",
      "setAutoHideMenuBar",
      "dispatchApplicationMenuCommand",
      "dispatchContextMenuCommand",
      "openLocations",
      "alive",
      "assignId",
      "isAlive",
      "isDestroyed"
```

Some of them are either private or not documented.

**Comment by banacorn** [comment]
Hi, how can I contribute to this repo? 
I want the typings so badly :D

**Comment by unional** [comment]
Sorry, didn't have time to work on it since last week.

I have added you to this and other related projects. Feed free to give them some love.

Remaining work:
- [ ] Fix `npm-text-buffer` repo
- [ ] Use `event-kit` `atom-keymap` `path-watcher` `text-buffer` and `first-mate` repo in this repo
- [ ] Fix up any remaining issues.

**Comment by unional** [comment]
Ah, I was having some difficulty on this: https://github.com/typings/discussions/issues/15#issuecomment-221955609

**Comment by unional** [comment]
Still have a few files left.

**Comment by unional** [comment]
@banacorn , I don't have time to work on it for the next few days, can you fix the files starting from `text-editor.d.ts`? There are only a few files left. Take a look at other files to see how to fix them.

Then we can test. Thanks.

**Comment by banacorn** [comment]
This is the best typings for Atom I can find on the planet, thanks for inviting me to this repo. I'll be happy to fix them.

**Comment by banacorn** [comment]
I've managed to clear all of the type errors, but I have no idea what should I do next (or what I've been doing).

Is there a brain dead simple typings publish tutorial? Or something like `typings publish`, this is all just too frustrating for me :(

**Comment by unional** [comment]
Huge thanks! I'll check it out. If it works, then the next and last step is updating https://github.com/typings/registry/blob/master/env/atom.json

**Comment by unional** [comment]
Good news. I got it working.

Checking in to registry now:
https://github.com/typings/registry/pull/544

**Comment by unional** [comment]
> Is there a brain dead simple typings publish tutorial? Or something like typings publish, this is all just too frustrating for me :(

I'm working on `generator-typings` and when I get the github part working, I'll be adding the publish function there. When it is ready, I believe the cmd would be:

`yo typings:publish` or something similar

**Comment by unional** [comment]
The test https://github.com/typed-typings/env-atom/blob/master/spec/atom-spec.ts#L21
covered this case. Closing this issue.

If you found other issue, feel free to open new ones. 🌷
